In [ ]:
from google.colab import files

uploaded = files.upload()

Saving S001R01.edf to S001R01.edf
Saving sub-01_task-motor-imagery_eeg.edf to sub-01_task-motor-imagery_eeg (1).edf

#### 1) load the eeg recording file:

	a) for stroke there is only one .edf per subject so no problem in loading that.

	b) for non-stroke there were many .edf files per subject according to the tasks they were told to perform so we choose recording 4 as it includes the hand movement task which matches our stroke data. (I will organise the dataset, upload it on drive and send it to you).

	c) used mne library to read .edf file

Gemini said
If you’re diving into the world of neuroscience or medical data science, MNE-Python is essentially the industry standard. It is an open-source Python library designed for exploring, visualizing, and analyzing human neurophysiological data.

Think of it as the "pandas" of the brain—it takes messy, high-dimensional sensor data and provides a structured way to clean it and extract meaning.

In [ ]:
import mne

stk= mne.io.read_raw_edf("sub-01_task-motor-imagery_eeg.edf", preload=True)
print(stk)
print(stk.ch_names)

Extracting EDF parameters from sub-01_task-motor-imagery_eeg.edf...
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 159999  =      0.000 ...   319.998 secs...
<RawEDF | sub-01_task-motor-imagery_eeg.edf, 33 x 160000 (320.0 s), ~40.3 MiB, data loaded>
['FP1', 'FP2', 'Fz', 'F3', 'F4', 'F7', 'F8', 'FCz', 'FC3', 'FC4', 'FT7', 'FT8', 'Cz', 'C3', 'C4', 'T3', 'T4', 'CPz', 'CP3', 'CP4', 'TP7', 'TP8', 'Pz', 'P3', 'P4', 'T5', 'T6', 'Oz', 'O1', 'O2', 'HEOL', 'HEOR', '']

/tmp/ipykernel_4352/821206738.py:3: RuntimeWarning: Physical range is not defined in following channels:
CPz
  stk= mne.io.read_raw_edf("sub-01_task-motor-imagery_eeg.edf", preload=True)

In [ ]:
non = mne.io.read_raw_edf("S001R04.edf", preload=True)
print(non)
print(non.ch_names)

Extracting EDF parameters from S001R04.edf...
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 19999  =      0.000 ...   124.994 secs...
<RawEDF | S001R04.edf, 64 x 20000 (125.0 s), ~9.8 MiB, data loaded>
['Fc5.', 'Fc3.', 'Fc1.', 'Fcz.', 'Fc2.', 'Fc4.', 'Fc6.', 'C5..', 'C3..', 'C1..', 'Cz..', 'C2..', 'C4..', 'C6..', 'Cp5.', 'Cp3.', 'Cp1.', 'Cpz.', 'Cp2.', 'Cp4.', 'Cp6.', 'Fp1.', 'Fpz.', 'Fp2.', 'Af7.', 'Af3.', 'Afz.', 'Af4.', 'Af8.', 'F7..', 'F5..', 'F3..', 'F1..', 'Fz..', 'F2..', 'F4..', 'F6..', 'F8..', 'Ft7.', 'Ft8.', 'T7..', 'T8..', 'T9..', 'T10.', 'Tp7.', 'Tp8.', 'P7..', 'P5..', 'P3..', 'P1..', 'Pz..', 'P2..', 'P4..', 'P6..', 'P8..', 'Po7.', 'Po3.', 'Poz.', 'Po4.', 'Po8.', 'O1..', 'Oz..', 'O2..', 'Iz..']

#### 2) converted the raw data to dataframe so that we could see the data in tabular form

In [ ]:
df1 = stk.to_data_frame()
display(df1.head())

,time,FP1,FP2,Fz,F3,F4,F7,F8,FCz,FC3,...,P3,P4,T5,T6,Oz,O1,O2,HEOL,HEOR,
0,0.000,109.646199,33.274428,26.171086,25.770216,33.690869,53.140408,44.004641,28.912124,56.928260,...,31.595659,16.370924,55.388723,13.744417,77.001381,61.776221,49.738699,41.491274,50.853410,1.0
1,0.002,108.225590,32.467397,25.274122,25.366379,32.164415,52.173119,43.268718,28.457992,56.509162,...,31.804089,17.850049,55.093000,16.243038,80.585666,63.789857,54.961710,42.375400,50.045256,0.0
2,0.004,107.014219,31.682277,24.384083,24.966600,30.655374,51.004562,42.787067,27.989116,56.042974,...,31.834345,19.519255,54.372297,19.103395,84.055559,65.347575,60.535976,43.229914,48.923255,0.0
3,0.006,106.287396,31.032270,23.632572,24.676406,29.339799,49.820985,42.603698,27.580692,55.623876,...,31.657852,21.153320,53.291243,21.919058,86.974676,66.216668,65.774259,43.949059,47.597254,0.0
4,0.008,106.254359,30.579456,23.139068,24.593203,28.368596,48.820652,42.694160,27.304969,55.343693,...,31.279653,22.501464,51.981053,24.248684,88.995602,66.292655,70.000774,44.460921,46.224176,0.0

In [ ]:
df2 = non.to_data_frame()
display(df2.head())

,time,Fc5.,Fc3.,Fc1.,Fcz.,Fc2.,Fc4.,Fc6.,C5..,C3..,...,P8..,Po7.,Po3.,Poz.,Po4.,Po8.,O1..,Oz..,O2..,Iz..
0,0.00000,-5.0,2.0,37.0,39.0,30.0,26.0,-16.0,-14.0,4.0,...,-21.0,-8.0,-35.0,-45.0,-66.0,-39.0,-33.0,-48.0,-39.0,-39.0
1,0.00625,-12.0,-24.0,1.0,-2.0,-15.0,-22.0,-55.0,-36.0,-27.0,...,-50.0,-40.0,-68.0,-65.0,-84.0,-52.0,-21.0,-42.0,-31.0,-34.0
2,0.01250,-77.0,-78.0,-59.0,-65.0,-63.0,-55.0,-67.0,-88.0,-71.0,...,-17.0,-22.0,-50.0,-35.0,-48.0,-18.0,-20.0,-42.0,-29.0,-27.0
3,0.01875,-66.0,-67.0,-50.0,-65.0,-60.0,-55.0,-68.0,-62.0,-53.0,...,-39.0,-60.0,-78.0,-64.0,-68.0,-41.0,-44.0,-62.0,-34.0,-43.0
4,0.02500,-45.0,-55.0,-33.0,-53.0,-54.0,-63.0,-83.0,-52.0,-50.0,...,-44.0,-55.0,-70.0,-54.0,-63.0,-37.0,-60.0,-70.0,-34.0,-45.0

#### 3) extracted the column names for both stroke and non-stroke which are the names of the electrodes

In [ ]:
print(list(df1.columns))

['time', 'FP1', 'FP2', 'Fz', 'F3', 'F4', 'F7', 'F8', 'FCz', 'FC3', 'FC4', 'FT7', 'FT8', 'Cz', 'C3', 'C4', 'T3', 'T4', 'CPz', 'CP3', 'CP4', 'TP7', 'TP8', 'Pz', 'P3', 'P4', 'T5', 'T6', 'Oz', 'O1', 'O2', 'HEOL', 'HEOR', '']

In [ ]:
print(list(df2.columns))

['time', 'Fc5.', 'Fc3.', 'Fc1.', 'Fcz.', 'Fc2.', 'Fc4.', 'Fc6.', 'C5..', 'C3..', 'C1..', 'Cz..', 'C2..', 'C4..', 'C6..', 'Cp5.', 'Cp3.', 'Cp1.', 'Cpz.', 'Cp2.', 'Cp4.', 'Cp6.', 'Fp1.', 'Fpz.', 'Fp2.', 'Af7.', 'Af3.', 'Afz.', 'Af4.', 'Af8.', 'F7..', 'F5..', 'F3..', 'F1..', 'Fz..', 'F2..', 'F4..', 'F6..', 'F8..', 'Ft7.', 'Ft8.', 'T7..', 'T8..', 'T9..', 'T10.', 'Tp7.', 'Tp8.', 'P7..', 'P5..', 'P3..', 'P1..', 'Pz..', 'P2..', 'P4..', 'P6..', 'P8..', 'Po7.', 'Po3.', 'Poz.', 'Po4.', 'Po8.', 'O1..', 'Oz..', 'O2..', 'Iz..']

#### 4) Clean non-stroke channel names as they had extra dots and spaces and made them uppercase so that we can pick the common electrodes from both by comparing

In [ ]:
cleaned_channels = [ch.replace('.', '').upper() for ch in non.ch_names]
print(cleaned_channels)

['FC5', 'FC3', 'FC1', 'FCZ', 'FC2', 'FC4', 'FC6', 'C5', 'C3', 'C1', 'CZ', 'C2', 'C4', 'C6', 'CP5', 'CP3', 'CP1', 'CPZ', 'CP2', 'CP4', 'CP6', 'FP1', 'FPZ', 'FP2', 'AF7', 'AF3', 'AFZ', 'AF4', 'AF8', 'F7', 'F5', 'F3', 'F1', 'FZ', 'F2', 'F4', 'F6', 'F8', 'FT7', 'FT8', 'T7', 'T8', 'T9', 'T10', 'TP7', 'TP8', 'P7', 'P5', 'P3', 'P1', 'PZ', 'P2', 'P4', 'P6', 'P8', 'PO7', 'PO3', 'POZ', 'PO4', 'PO8', 'O1', 'OZ', 'O2', 'IZ']

#### 5) Now we will clean the stroke channels.
current stroke list has:

'HEOL', 'HEOR', ''

👉 These are: • EOG (eye movement)

In [ ]:
stroke_channels_clean = [ch for ch in stk.ch_names if ch not in ['HEOL', 'HEOR', '']]
print(stroke_channels_clean)

['FP1', 'FP2', 'Fz', 'F3', 'F4', 'F7', 'F8', 'FCz', 'FC3', 'FC4', 'FT7', 'FT8', 'Cz', 'C3', 'C4', 'T3', 'T4', 'CPz', 'CP3', 'CP4', 'TP7', 'TP8', 'Pz', 'P3', 'P4', 'T5', 'T6', 'Oz', 'O1', 'O2']

#### 6) Now we will standardize stroke channel names to match non-stroke.
Right now you have:

'Fz', 'Cz', 'Pz', 'Oz'

But in non-stroke:

'FZ', 'CZ', 'PZ', 'OZ'

👉 Case mismatch will cause problems later.

In [ ]:
stroke_channels_clean = [ch.upper() for ch in stroke_channels_clean]
print(stroke_channels_clean)

['FP1', 'FP2', 'FZ', 'F3', 'F4', 'F7', 'F8', 'FCZ', 'FC3', 'FC4', 'FT7', 'FT8', 'CZ', 'C3', 'C4', 'T3', 'T4', 'CPZ', 'CP3', 'CP4', 'TP7', 'TP8', 'PZ', 'P3', 'P4', 'T5', 'T6', 'OZ', 'O1', 'O2']

#### 7) Common channels between stroke and non-stroke
We want:

👉 Channels present in both datasets

👉 So data becomes comparable

In [ ]:
common_channels = list(set(stroke_channels_clean).intersection(set(cleaned_channels)))
print(sorted(common_channels))

['C3', 'C4', 'CP3', 'CP4', 'CPZ', 'CZ', 'F3', 'F4', 'F7', 'F8', 'FC3', 'FC4', 'FCZ', 'FP1', 'FP2', 'FT7', 'FT8', 'FZ', 'O1', 'O2', 'OZ', 'P3', 'P4', 'PZ', 'TP7', 'TP8']

#### 8) Now we will fix the order of channels.
👉 Right now your channels are unordered (random order from set)

👉 This can break:

• topographic maps ❌

• ML model consistency ❌

In [ ]:
ordered_channels = [ch for ch in stroke_channels_clean if ch in common_channels]
print(ordered_channels)

['FP1', 'FP2', 'FZ', 'F3', 'F4', 'F7', 'F8', 'FCZ', 'FC3', 'FC4', 'FT7', 'FT8', 'CZ', 'C3', 'C4', 'CPZ', 'CP3', 'CP4', 'TP7', 'TP8', 'PZ', 'P3', 'P4', 'OZ', 'O1', 'O2']

#### 9) Convert all channel names in the raw object to uppercase and pick using the uppercase list directly

In [ ]:
stk.rename_channels({ch: ch.upper() for ch in stk.ch_names})

stk.pick(ordered_channels)
print(stk.ch_names)

['FP1', 'FP2', 'FZ', 'F3', 'F4', 'F7', 'F8', 'FCZ', 'FC3', 'FC4', 'FT7', 'FT8', 'CZ', 'C3', 'C4', 'CPZ', 'CP3', 'CP4', 'TP7', 'TP8', 'PZ', 'P3', 'P4', 'OZ', 'O1', 'O2']

#### 10) Convert all channel names in the raw object to uppercase and remove trailing dots and pick using the uppercase list

In [ ]:
non.rename_channels({ch: ch.replace('.', '').upper() for ch in non.ch_names})

non.pick(ordered_channels)
print(non.ch_names)

['FP1', 'FP2', 'FZ', 'F3', 'F4', 'F7', 'F8', 'FCZ', 'FC3', 'FC4', 'FT7', 'FT8', 'CZ', 'C3', 'C4', 'CPZ', 'CP3', 'CP4', 'TP7', 'TP8', 'PZ', 'P3', 'P4', 'OZ', 'O1', 'O2']